import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";

// Import Fira Code with desired subsets
const firaCode = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "To-Do List",
  icons: {
    icon: "/favicon.ico",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={firaCode.className}>{children}</body>
    </html>
  );
}
